### ISSUE TITLE
NSRangeException

### ISSUE THREAD

**Issue by gloparco** [optonaut/ActiveLabel.swift#14] opened 2015-10-19 14:45 UTC
Hi Johannes, thanks for ActiveLabel - nice work!

I notice that when using ActiveLabel in a CollectionView and scrolling up or down, I sometimes get the following error:

*** Terminating app due to uncaught exception 'NSRangeException', reason: 'NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds'

This has also been documented in another UILabel github lib (Obj-C), here:

https://github.com/SebastienThiebaud/STTweetLabel/issues/55

The bug is hard to reproduce, but it has happened multiple times.  It doesn't appear to be associated with the speed of scrolling or anything else I can reproduce, but as I mentioned, it has happened multiple times now, and it does seem related to ActiveLabel.  Sorry I can't be of more help.

**Comment by gloparco** [comment] 2015-10-19 14:55
Just to add to it, here is a long discussion on the topic (from a site that I had never heard of before):

http://youranswers.info/question/view/en/YUhSMGNEb3ZMM04wWVdOcmIzWmxjbVpzYjNjdVkyOXRMM0YxWlhOMGFXOXVjeTh4T0RrMk1qYzBNaTkxYVhSbGVIUjJhV1YzTFd4cGJtc3RaR1YwWldOMGFXOXVMV2x1TFdsdmN5MDM=

I'm not sure if this can be prevented by your code, but it might be worth looking into.  It seems to have something to do with AttributedString, but it does not appear to be certain.

**Comment by schickling** [comment] 2015-10-19 15:45
Hi @gloparco! Thanks for reporting this.
We're using ActiveLabel just as part of a UITableView, so we haven't had this issue so far and unfortunately don't have the capacity at the moment to look into it in depth.

However we'd be more than happy to merge a PR which resolves this issue.

**Comment by byAmmerix** [comment] 2016-02-03 11:29
@gloparco I am using ActiveLabel in an UITableViewCell but every time i set a text containing an @ or # I get a NSRangeException.

**Comment by poolqf** [comment] 2016-02-04 23:30
Hi @byAmmerix, in what SDK and iOS version have you noticed it?

**Comment by byAmmerix** [comment] 2016-02-05 10:06
I am using:
Cocoapods: ```pod 'ActiveLabel', '~> 0.4'```
iOS version/SDK: 9.2

**Comment by alexbredy** [comment] 2016-02-11 14:55
+1 happens to me every time i close and reopen a given tableview repeatedly.

**Comment by poolqf** [comment] 2016-02-12 10:27
@alexbredy what dependency manager are you using? iOS and SDK version?

**Comment by alexbredy** [comment] 2016-02-12 11:21
Hi @poolqf 

Using Cocoapods with
iOS version 9.2.1 and SDK 9.2 (Xcode 7.2.1)

Update regarding the issue I'm having: 
The crash does not occur if I'm not adding cells upon opening the tableview. Somehow when I keep adding rows with the same url it crashes after 4-5 times closing and reopening the tableview.

The crash does **not** happen if the cells are unaltered.

**Comment by adergaard** [comment] 2016-02-12 13:25
The problem is most likely due to row 190 in ActiveLabel.swift:

`dispatch_async`

Quickfix: Comment out that row (and consequently the closing } on row 194) and let the commands execute on the main thread instead and the crash is no more. 

Be very careful trying to do stuff outside the main thread.

**Comment by poolqf** [comment] 2016-02-17 19:17
I've removed the `dispatch_async` in #47 
I am now going to create a new release. Closing this issue.

Feel free to reopen it if it happens again

cc/ @byAmmerix , @alexbredy , @JaviSoto

**Closed by poolqf** 2016-02-17 19:17 UTC
