### ISSUE TITLE
Duplicate text label when I'm using TableView or CollectionView

### ISSUE THREAD

**Issue by viniciuszim** [optonaut/ActiveLabel.swift#49] opened 2016-02-24 21:44 UTC
The API doesn't work so well when I'm using TableView or CollectionView... sometimes the label doesn't have text and the cell is getting the old value for this label... duplicating my text and showing wrong.

To fix that... I've had to improve some part of the code... see my solution:

override public var text: String? {
        didSet {
            if text != nil && text != "" {
                updateTextStorage()
            } else {
                self.textStorage.setAttributedString(NSAttributedString())
            }
        }
    }

I hope help someone else and/or improve your code... Great API that you make... Congrats

**Comment by poolqf** [comment] 2016-10-14 20:04
Not able to reproduce, closing

**Closed by poolqf** 2016-10-14 20:04 UTC
