### ISSUE TITLE
Does not support Chinese

### ISSUE THREAD

**Issue by weifans** [optonaut/ActiveLabel.swift#2] opened 2015-09-11 04:57 UTC
Thank you develop the library, but does not support Chinese, looked at them, use regular expressions, no modification is successful, I hope you can support the Chinese as soon as possible, thank you.

**Comment by schickling** [comment] 2015-09-11 08:44
Hi @weiFans. Thanks for reporting this issue. It should be resolved by tackling #1 in the future.

**Comment by Estanque** [comment] 2015-10-31 11:11
Please fix this issue for Russian language too.

**Comment by mamouneyya** [comment] 2015-12-01 11:33
Suggestion for the detection regular expression: [\\w\\_]+

**Comment by nanhuo** [comment] 2016-01-28 09:43
If you only need Chinese and English support, check this https://github.com/nanhuo/ActiveLabel.swift

**Comment by dsinkovskiy** [comment] 2016-05-01 21:44
Please check my pull request #78. The problem is solved. You can override regex patterns as you wish. And there are some really good regex for hashtags and mantions with multilanguage support in Tests.

**Closed** 2018-10-20 18:45 UTC
