### ISSUE TITLE
URL Detection

### ISSUE THREAD

**Issue by krjackso** [optonaut/ActiveLabel.swift#64] opened 2016-04-15 03:40 UTC
I noticed in my app that the word "picture" is detected as a URL.  After looking into it, I noticed that any phrase starting with "www" or "pic" will get detected as a URL, even though they are not valid URLs.  Looking at the history, we used to use NSDataDetector but switched to a regex. Is there a compelling reason not to use NSDataDetector for this? The only test that fails using NSDataDetector is that "google.com" gets detected as a URL when the test does not want it to be (I would actually prefer it to be).  Right now I am running with my fork that uses NSDataDetector until this can be resolved.

**Comment by poolqf** [comment] 2016-04-15 07:55
Hi @krjackso, I am sorry for the issue, we should take a look at the regex for the urls. The reason why we switched from NSDataDetector to regex is that data detector is 2x more expensive.

See https://github.com/optonaut/ActiveLabel.swift/pull/40#issuecomment-170157961
> Seems like NSDataDetector is slower than a custom Regex (2x the time)... Maybe we should move to a regex for the URLs?

**Comment by krjackso** [comment] 2016-04-15 18:32
Yeah URL regexes are a real pain :) Perhaps a decent compromise would be opening up the RegexParser so that we can override the different types of detectors if we need them to be different? The other thing I like about using NSDataDetector for URLs is it will be consistent with other things using it to detect links which will be important for my users who are mostly coming from the bundled iOS apps.

**Comment by poolqf** [comment] 2016-04-15 20:39
Yep, i like the idea, but in order to fix and add tests for it, I would like to know first which text is being detected as url, and it is not. Even if we open the Regex parser, there should be a default regex.

**Comment by Abdul-Moiz** [comment] 2016-06-03 14:35
Hi, I am still detecting "picture." highlighted as a URL. 
![picturedetection](https://cloud.githubusercontent.com/assets/3176559/15782010/9a58a012-2976-11e6-9f40-b2de72b957e1.png)
This issue is still not resolved.

**Comment by poolqf** [comment] 2016-10-14 20:01
Not able to reproduce, closing...

**Closed by poolqf** 2016-10-14 20:01 UTC
