### ISSUE TITLE
@mention not detecting complete text if it is separated with a dot or any special character between the text.

### ISSUE THREAD

**Issue by Jitenderios** [optonaut/ActiveLabel.swift#230] opened 2018-01-09 07:21 UTC
Add detection for @username.username.
Eg: If the mention text is - @username.username
In this case it only detects "username"  and not "username.username". Please look into this.

Thanks 
Jitender

**Comment by demonar** [comment] 2018-02-21 05:49
duplicate of https://github.com/optonaut/ActiveLabel.swift/issues/9 and https://github.com/optonaut/ActiveLabel.swift/issues/228

**Comment by bungkhus** [comment] 2018-04-06 15:00
Hi @Jitenderios @demonar ,
I just found the solution!
Go to the ActivityLabel/RegexParser.swift file and add a dot (.) to the _mentionPattern_
`static let mentionPattern = "(?: ^ | \\ s | $ | [.]) @ [\\ p {L} 0-9 _.] *"`

**Comment by Jitenderios** [comment] 2018-04-10 06:16
Hi @bungkhus ,

Thanks for your answer.

Thanks,
Jitender

**Comment by pvcary** [comment] 2018-05-10 13:58
Hi @bungkhus

What would you do in the case of recognizing a white space? Could this be added to the mention pattern as well? Something like "\u{00a0}". Im trying to achieve a space between the first and last name to be recognizable by ActiveLabel.

Thanks,
Patrick

**Comment by demonar** [comment] 2018-05-10 15:52
@pvcary i think that case falls in the custom pattern, the social networks doesn't allow spaces in the user handles

**Closed** 2018-09-06 12:05 UTC
